import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css';
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { getServerSession } from "next-auth";
import SessionProvider from '@/components/SessionProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getServerSession();

    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
            </head>
            <body className={inter.className}>
                <MantineProvider>
                    <SessionProvider session={session}>
                        {/*<main className="mx-auto max-w-5xl text-2xl flex gap-2">
                            <NavMenu />*/}
                            {children}
                        {/*</main>*/}
                    </SessionProvider>
                </MantineProvider>

            </body>
        </html>
    )
}
